version: '3'
services:
  octoprint:
    build: ./octoprint/
    ports:
    - "5000:5000"
    volumes:
    - ./octoprint/config/config.yaml:/root/.octoprint/config.yaml
    devices:
    - /dev/ttyUSB0:/dev/ttyUSB0
  mjpg_streamer:
    build: ./mjpg_streamer/
    ports:
    - "8081:8081"
    devices:
    - /dev/video0:/dev/video0
